project_id = "zyxiznikuvpwmopraauj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions.send-qna-notifications]
verify_jwt = false

[functions.ip-geolocation]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = true

[functions.process-missing-embeddings]
verify_jwt = true

[functions.chat-rag]
verify_jwt = false

[functions.chat-rag-v2]
verify_jwt = false

[functions.migrate-existing-knowledge]
verify_jwt = true

[functions.lookup-nace]
verify_jwt = true

[functions.create-user-account]
verify_jwt = true

[functions.manage-user-roles]
verify_jwt = true

[functions.generate-example-questions]
verify_jwt = false

[functions.custom-rag-operations]
verify_jwt = true

[functions.vertex-rag-query]
verify_jwt = false

[functions.send-announcement-email]
verify_jwt = true

[functions.tcmb-exchange]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false

[functions.ai-support-draft]
verify_jwt = true
